apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5"]
        ports:
        - containerPort: 9001
        env:
          - name: BPL_JVM_THREAD_COUNT
            value: "50"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://polar-postgres:5432/polardb_catalog
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://config-service
          - name: SPRING_PROFILES_ACTIVE
            value: testdata
